// Generated by gencpp from file custom_msg/llpath.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_LLPATH_H
#define CUSTOM_MSG_MESSAGE_LLPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msg/llpoint.h>

namespace custom_msg
{
template <class ContainerAllocator>
struct llpath_
{
  typedef llpath_<ContainerAllocator> Type;

  llpath_()
    : header()
    , id(0)
    , amount(0)
    , Forward(0)
    , points()  {
    }
  llpath_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , amount(0)
    , Forward(0)
    , points()  {
  (void)_alloc;
      points.assign( ::custom_msg::llpoint_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _amount_type;
  _amount_type amount;

   typedef int8_t _Forward_type;
  _Forward_type Forward;

   typedef boost::array< ::custom_msg::llpoint_<ContainerAllocator> , 200>  _points_type;
  _points_type points;




  typedef boost::shared_ptr< ::custom_msg::llpath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::llpath_<ContainerAllocator> const> ConstPtr;

}; // struct llpath_

typedef ::custom_msg::llpath_<std::allocator<void> > llpath;

typedef boost::shared_ptr< ::custom_msg::llpath > llpathPtr;
typedef boost::shared_ptr< ::custom_msg::llpath const> llpathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::llpath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::llpath_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_msg': ['/home/george/catkin_ws/src/custom_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::llpath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::llpath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::llpath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::llpath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::llpath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::llpath_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::llpath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27f4ad79af1acdc81e50e42085dd392e";
  }

  static const char* value(const ::custom_msg::llpath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27f4ad79af1acdc8ULL;
  static const uint64_t static_value2 = 0x1e50e42085dd392eULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::llpath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/llpath";
  }

  static const char* value(const ::custom_msg::llpath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::llpath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 id\n\
int32 amount\n\
int8 Forward\n\
llpoint[200] points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: custom_msg/llpoint\n\
Header header\n\
float32 x\n\
float32 y\n\
float32 theta\n\
float32 r\n\
float32 velocity\n\
float32 distance\n\
";
  }

  static const char* value(const ::custom_msg::llpath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::llpath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.amount);
      stream.next(m.Forward);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct llpath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::llpath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::llpath_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "amount: ";
    Printer<int32_t>::stream(s, indent + "  ", v.amount);
    s << indent << "Forward: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Forward);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msg::llpoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_LLPATH_H
